# Generated by Django 4.1.3 on 2023-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rasoiyo_papadseller_maitinwaro_maitinwari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
