# Generated by Django 4.1.3 on 2023-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_professional_remove_ladasinger_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Sindhi_Sub_Caste',
            field=models.CharField(default='', max_length=100),
        ),
    ]
