# Generated by Django 4.1.3 on 2023-05-19 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_sindhi_sub_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='Sindhi_Sub_Caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='birthdate',
            field=models.DateField(default=None, help_text='BirthDate'),
        ),
        migrations.AddField(
            model_name='professional',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='ref_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='professional',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
