# Generated by Django 4.1.3 on 2023-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_professional_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='ref_num',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
