# Generated by Django 4.1.3 on 2023-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_professional_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(choices=[('estate_agent', 'Estate Agent'), ('papad_seller', 'Papad Seller'), ('maharaj_swami', 'Maharaj Swami'), ('lada_singer', 'Lada Singer'), ('rasoiyo', 'Rasoiyo'), ('maitinwaro', 'Maitinwaro'), ('maitinwari', 'Maitinwari')], default='', max_length=50),
        ),
    ]
