# Generated by Django 4.1.3 on 2023-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_professional_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='other_profession',
        ),
        migrations.AddField(
            model_name='professional',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profession',
            field=models.CharField(choices=[('estate_agent', 'Estate Agent'), ('papad_seller', 'Papad Seller'), ('maharaj_swami', 'Maharaj Swami'), ('lada_singer', 'Lada Singer'), ('rasoiyo', 'Rasoiyo'), ('maitinwaro', 'Maitinwaro'), ('maitinwari', 'Maitinwari'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('genuine_properties', 'Genuine Properties'), ('safe_tourism', 'Safe Tourism'), ('social_workers', 'Social Workers'), ('education', 'Education'), ('food_industries', 'Food Industries'), ('advocates', 'Advocates')], default='', max_length=50),
        ),
    ]
