# Generated by Django 4.1.3 on 2023-06-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_professional_custom_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='Sindhi_Sub_Caste',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='ref_num',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='user',
        ),
    ]
