# Generated by Django 4.1.3 on 2023-06-05 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_remove_professional_sindhi_sub_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='Sindhi_Sub_Caste',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='professional',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='ref_num',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
