# Generated by Django 4.1.3 on 2023-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_professional_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
